# Generated by Django 2.2.4 on 2019-10-13 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCidade', models.CharField(choices=[('indaiatuba', 'Indaiatuba')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('cadastro_criado', models.DateTimeField()),
                ('avatar', models.ImageField(blank=True, default='pics/None/no-img.png', null=True, upload_to='pics/clientes/')),
                ('ultimo_compra', models.DateTimeField(auto_now=True)),
                ('quantidade_comentarios', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_data_oferta', models.DateField(null=True)),
                ('inicio_horario_oferta', models.TimeField(null=True)),
                ('fim_data_oferta', models.DateField(null=True)),
                ('fim_horario_oferta', models.TimeField(null=True)),
                ('preco_oferta', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('total_vendas', models.IntegerField(blank=True)),
                ('descricao', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='pics/None/no-img.png', upload_to='pics/restaurante/')),
                ('cnpj', models.CharField(max_length=18)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(default='pics/None/no-img.png', upload_to='pics/produtos/')),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Categoria')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Placed_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('tempo_estimado', models.IntegerField(blank=True)),
                ('comida_pronta', models.DateTimeField(auto_now=True)),
                ('endereco_entrega', models.CharField(max_length=255)),
                ('endereco_saida', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cliente')),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('comercial', 'Comercial'), ('outro', 'Outro')], max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cidade')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Em_Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Oferta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cliente')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Produto')),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Restaurante')),
                ('placed_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Placed_order')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('descricao', models.TextField(blank=True)),
                ('recomenda', models.BooleanField(default=True)),
                ('data_comentario', models.DateTimeField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cliente')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Produto')),
                ('restaurante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Endereco'),
        ),
    ]
