# Generated by Django 2.2.4 on 2019-10-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191013_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
