# Generated by Django 2.2.4 on 2019-11-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20191102_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='especialidade',
            field=models.CharField(choices=[('saldados', 'Salgados'), ('saladas', 'Saladas'), ('italiana', 'Italiana'), ('doces', 'Doces'), ('lanches', 'Lanches'), ('sorvetes', 'Sorvetes'), ('bebidas', 'Bebidas'), ('chinesa', 'Chinesa'), ('japonesa', 'Japonesa'), ('petiscos', 'Petiscos'), ('pizzas', 'Pizzas'), ('massas', 'Massas'), ('pratos', 'Pratos'), ('outros', 'Outros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(default='pics/None/no-img.png', upload_to='pics/restaurantes'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Restaurante')),
            ],
        ),
    ]
