# Generated by Django 2.2.4 on 2019-11-03 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_auto_20191103_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='id_restaurante',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='id_user',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
