# Generated by Django 2.2.4 on 2019-11-04 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20191103_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
