# Generated by Django 2.2.4 on 2019-11-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20191103_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('saldados', 'Salgados'), ('saladas', 'Saladas'), ('italiana', 'Italiana'), ('doces', 'Doces'), ('lanches', 'Lanches'), ('sorvetes', 'Sorvetes'), ('bebidas', 'Bebidas'), ('chinesa', 'Chinesa'), ('japonesa', 'Japonesa'), ('petiscos', 'Petiscos'), ('pizzas', 'Pizzas'), ('massas', 'Massas'), ('pratos', 'Pratos'), ('outros', 'Outros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('saldados', 'Salgados'), ('saladas', 'Saladas'), ('italiana', 'Italiana'), ('doces', 'Doces'), ('lanches', 'Lanches'), ('sorvetes', 'Sorvetes'), ('bebidas', 'Bebidas'), ('chinesa', 'Chinesa'), ('japonesa', 'Japonesa'), ('petiscos', 'Petiscos'), ('pizzas', 'Pizzas'), ('massas', 'Massas'), ('pratos', 'Pratos'), ('outros', 'Outros')], max_length=255),
        ),
    ]
