# Generated by Django 2.2.4 on 2019-11-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20191103_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nota',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
