# Generated by Django 2.2.4 on 2019-11-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_produto_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='lixeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('salgados', 'Salgados'), ('saladas', 'Saladas'), ('italiana', 'Italiana'), ('doces', 'Doces'), ('lanches', 'Lanches'), ('sorvetes', 'Sorvetes'), ('bebidas', 'Bebidas'), ('chinesa', 'Chinesa'), ('japonesa', 'Japonesa'), ('petiscos', 'Petiscos'), ('pizzas', 'Pizzas'), ('massas', 'Massas'), ('pratos', 'Pratos'), ('outros', 'Outros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('salgados', 'Salgados'), ('saladas', 'Saladas'), ('italiana', 'Italiana'), ('doces', 'Doces'), ('lanches', 'Lanches'), ('sorvetes', 'Sorvetes'), ('bebidas', 'Bebidas'), ('chinesa', 'Chinesa'), ('japonesa', 'Japonesa'), ('petiscos', 'Petiscos'), ('pizzas', 'Pizzas'), ('massas', 'Massas'), ('pratos', 'Pratos'), ('outros', 'Outros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='especialidade',
            field=models.CharField(choices=[('salgados', 'Salgados'), ('saladas', 'Saladas'), ('italiana', 'Italiana'), ('doces', 'Doces'), ('lanches', 'Lanches'), ('sorvetes', 'Sorvetes'), ('bebidas', 'Bebidas'), ('chinesa', 'Chinesa'), ('japonesa', 'Japonesa'), ('petiscos', 'Petiscos'), ('pizzas', 'Pizzas'), ('massas', 'Massas'), ('pratos', 'Pratos'), ('outros', 'Outros')], max_length=255),
        ),
    ]
