# Generated by Django 2.2.4 on 2019-11-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20191105_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_compra', models.DateTimeField(auto_now=True)),
                ('is_carrinho', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cliente')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Produto')),
            ],
        ),
    ]
