# Generated by Django 2.2.4 on 2019-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='ultimo_compra',
            new_name='adicionado_carrinho',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
