# Generated by Django 2.2.4 on 2019-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20191109_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
