# Generated by Django 2.2.4 on 2019-11-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_order',
            name='preco',
        ),
        migrations.AddField(
            model_name='placed_order',
            name='id_produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='delivery.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placed_order',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='placed_order',
            name='order_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='placed_order',
            name='tempo_estimado',
            field=models.IntegerField(blank=True, default=15),
        ),
    ]
