# Generated by Django 2.2.4 on 2019-11-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_auto_20191111_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='id_restaurante',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebido', models.BooleanField(default=False)),
                ('saiu', models.BooleanField(default=False)),
                ('em_rota', models.BooleanField(default=False)),
                ('entregue', models.BooleanField(default=False)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Placed_order')),
            ],
        ),
    ]
