# Generated by Django 2.2.4 on 2019-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20191115_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_order',
            name='comida_pronta',
        ),
        migrations.AddField(
            model_name='placed_order',
            name='pedido_pronta',
            field=models.BooleanField(default=False),
        ),
    ]
