# Generated by Django 2.2.4 on 2019-11-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20191115_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.AddField(
            model_name='placed_order',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.Order'),
            preserve_default=False,
        ),
    ]
