# Generated by Django 2.2.4 on 2019-11-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_auto_20191115_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Order'),
        ),
    ]
