# Generated by Django 2.2.4 on 2019-11-24 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_auto_20191117_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='placed_order',
            name='order_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
