# Generated by Django 2.2.4 on 2019-12-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20191124_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
