version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: foodz_3.0
        MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql